In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [96]:
"""
img: The input grayscale image.
GL: Number of gray levels.
d: The distance between pixel pairs.
t: The angle (in degrees) specifying the direction of pixel pairs.
"""
def am_glcm_faster( img , GL , d , t):
    ccmm = np.zeros([GL, GL])
    #Make sure it's not out of boundary
    if t==0:
        im_target = img[:,d:]
        im_value = img[:,:-d]
        
    elif t==45:
        im_target = img[d:,d:]
        im_value = img[:-d, :-d]
    elif t==90:
        im_target = img[d:,:]
        im_value = img[:-d, :]
    elif t==135:
        im_target = img[:-d, :-d]
        im_value = img[d:,d:]
    else:
        raise NotImplementedError('t options: 0, 45, 90, 135 only')
    assert im_target.shape==im_value.shape
    ref_gls = np.unique(im_value)
    # print(ref_gls)
    for ref in ref_gls:
        #ref: 80
        target_values = im_target[im_value == ref]#select the position that have the specific value. Prepare for later's d and t
        #target_values: [ 98,  89,  99, 100]
        target_gls = np.unique(target_values)
        #[ 89,  98,  99, 100]
        for target in target_gls:
               ccmm[ref, target] = (target_values==target).sum()
    return ccmm

import numpy as np

def compute_glcm(input_matrix, d, theta):
    """
    Compute the Gray Level Co-occurrence Matrix (GLCM) for an input matrix.
    
    :param input_matrix: 2D numpy array of the image
    :param d: distance between pixel of interest and its neighbor
    :param theta: angle between pixel of interest and its neighbor (in degrees)
    :return: GLCM matrix
    """
    rows, cols = input_matrix.shape
    max_value = input_matrix.max() + 1  # Maximum intensity value in the matrix
    glcm = np.zeros((max_value, max_value), dtype=int)

    # Define the direction based on theta
    if theta == 0:
        dx, dy = d, 0
    elif theta == 45:
        dx, dy = d, -d
    elif theta == 90:
        dx, dy = 0, -d
    elif theta == 135:
        dx, dy = -d, -d
    else:
        raise ValueError("Theta should be 0, 45, 90, or 135 degrees")

    # Iterate over the matrix and fill the GLCM
    for x in range(rows):
        for y in range(cols):
            if 0 <= x + dx < rows and 0 <= y + dy < cols:
                row = input_matrix[x, y]
                col = input_matrix[x + dx, y + dy]
                glcm[row, col] += 1

    return glcm


In [98]:
matrix = np.array(
    [[1,0,0,3,4],
     [1,3,0,3,4],
     [2,3,0,3,4],
     [1,3,0,2,2],
     [2,3,1,2,2]])
print(am_glcm_faster(matrix, 6, 1, 135))

[[1. 0. 0. 2. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [2. 0. 1. 1. 0. 0.]
 [2. 3. 1. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [73]:
mat2 = np.array([[1, 1, 1],
                 [1, 1, 1],
                 [1, 1, 0]])
print(am_glcm_faster(mat2, 2, 1, 45))

[[0. 0.]
 [1. 3.]]


In [79]:
print(compute_glcm(matrix, 1, 0))

[[3 1 0 1 0]
 [0 1 2 0 0]
 [0 1 2 0 0]
 [0 0 1 5 0]
 [0 0 1 0 2]]
