## Convolution & Filtering, Example 1
### 1. Filtering and convolution 

In [1]:
# Libraries 
import cv2
import numpy as np
import scipy.signal as sig

In [2]:
# function to compute the power of an image, ither RGb or graylevel
def am_power2(a):
    dim1 = a.shape
    if len(dim1)==2:
        sz = dim1[0] * dim1[1] 
    else:
        sz = dim1[0] * dim1[1] * dim1[2]
    pa = np.sum( np.double(a)**2 )
    pa = pa / sz
    return pa 

In [3]:
b=np.asarray([[1,2,0,1,2],
              [2,3,1,1,2],
              [1,4,2,2,0],
              [3,2,3,3,0],
              [1,0,0,2,1]
              ])

w=np.asarray([[-1,0,0],
              [1,1,2],
              [2,1,0]])


In [4]:
# print size of image and filter and results of convolution using 3 options/switches
#
print('b and w size:\n\n', b.shape , w.shape)
print(sig.convolve2d(b,w,mode="valid"))


b and w size:

 (5, 5) (3, 3)
[[ 8  8 10]
 [10 12 11]
 [19 14 10]]


In [5]:
print(sig.convolve2d(b,w,mode="same"))

[[ 0  3  4  1  4]
 [ 6  8  8 10  6]
 [11 10 12 11  6]
 [14 19 14 10  6]
 [ 8 10 11  6  5]]


In [6]:
print(sig.convolve2d(b,w , mode='full') )

[[-1 -2  0 -1 -2  0  0]
 [-1  0  3  4  1  4  4]
 [ 3  6  8  8 10  6  4]
 [ 2 11 10 12 11  6  0]
 [ 4 14 19 14 10  6  0]
 [ 7  8 10 11  6  5  2]
 [ 2  1  0  4  4  1  0]]


In [7]:
### 2- Convolution and filtering of an image
#### using opencv filter2D function 

In [8]:
# load the image
image = cv2.imread('..\\guernica.jpg')

# Print error message if image is null
if image is None:
    print('Could not read image')

# filters / kernels 
kernel1 = np.array([[-1, -1, -1],
                    [-1, 9, -1],
                    [-1, -1, -1]]) 

lp1 = np.ones([2,2]) * 0.25
lp2 = np.ones([7,7]) / 49 

hp2 = np.array([[-1, 1], [1, -1]]) 

In [9]:
## opencv filter2D function
## cv.filter2D(	src, ddepth, kernel[, dst[, anchor[, delta[, borderType]]]]	) ->	dst
## src = image, 2d or 3d   ,   ddepth = 
## kernel = filter

In [10]:
image2 = cv2.filter2D(src=image, ddepth=-1, kernel= lp1)
cv2.namedWindow("Original", cv2.WINDOW_NORMAL)
cv2.imshow('Original', image)
cv2.namedWindow("Filtered", cv2.WINDOW_NORMAL)
cv2.imshow('Filtered', image2)

In [11]:
print('original and filterd image size=', image.shape , image2.shape)

original and filterd image size= (1200, 3200, 3) (1200, 3200, 3)


In [12]:
#diff = np.uint8(np.abs(image-image2))
diff = np.uint8(image-image2) 
cv2.namedWindow("difference", cv2.WINDOW_NORMAL)
cv2.imshow('difference', diff)
cv2.waitKey()

32

In [13]:
print( 'images power: original= %10.3f  ,  filtered= %10.3f  ,  difference= %10.3f' 
      %( am_power2(image) , am_power2( image2) , am_power2(diff)) )

images power: original=  22017.342  ,  filtered=  21951.417  ,  difference=  23674.969


In [14]:
cv2.destroyAllWindows()