In [1]:
import numpy as np

# Given values
x = np.array([0.5, 0.7])       # Inputs
U = np.array([[1, -1], [1, -1]])  # Weights for first layer
W = np.array([-0.5, 0.5])      # Weights for second layer
target_y = 1                   # Target output
learning_rate = 0.25           # Learning rate

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Forward pass
f1 = sigmoid(U.T @ x)
y = sigmoid(W @ f1)

# Loss function (Mean Squared Error)
L = 0.5 * (target_y - y) ** 2

# Correct backward pass calculations

# Gradient of the loss with respect to the output of the neural network
dL_dy = -(target_y - y)

# Gradient of the output with respect to the weights W
dy_dW = f1 * y * (1 - y)

# Gradient of the loss with respect to the weights W
dL_dW = dL_dy * dy_dW

# Update weights W
W_new = W - learning_rate * dL_dW

# Gradient of the output with respect to the hidden layer outputs f1
dy_df1 = W * y * (1 - y)

# Gradient of the hidden layer outputs with respect to the hidden layer weights U
df1_dU = np.outer(x, (f1 * (1 - f1)))

# Gradient of the loss with respect to the hidden layer weights U
dL_dU = np.outer(dL_dy * dy_df1, f1 * (1 - f1))

# Update weights U
U_new = U - learning_rate * dL_dU.T

# Output the loss, and the new weights for U and W
dL_dy, dy_df1, df1_dU, L, U_new, W_new


(-0.5667307056816238,
 array([-0.12277351,  0.12277351]),
 array([[0.08894722, 0.08894722],
        [0.12452611, 0.12452611]]),
 0.1605918463811956,
 array([[ 0.99690555, -0.99690555],
        [ 0.99690555, -0.99690555]]),
 array([-0.47326321,  0.50805297]))